<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Acquired Books Report</title>
    <style>
        body { font-family: 'Segoe UI', system-ui, sans-serif; margin: 40px; color: #1f2937; }
        h1 { color: #800000; border-bottom: 3px solid #FFC72C; padding-bottom: 8px; }
        .period-line { color: #6b7280; font-size: 0.95rem; margin-bottom: 16px; }
        table { width: 100%; border-collapse: collapse; margin: 20px 0; font-size: 0.88rem; }
        th { background: #800000; color: white; padding: 9px 12px; text-align: left; font-weight: 600; font-size: 0.85rem; }
        td { padding: 9px 12px; border-bottom: 1px solid #e5e7eb; }
        tr:nth-child(even) { background: #f9fafb; }
        .empty-msg { padding: 24px; text-align: center; color: #6b7280; font-style: italic; }
        .footer { margin-top: 40px; font-size: 0.8rem; color: #6b7280; text-align: center; border-top: 1px solid #e5e7eb; padding-top: 16px; }
    </style>
</head>
<body>
<h1>Acquired Books Report</h1>
<p class="period-line"><strong>Period:</strong> {{ $periodLabel ?? 'All Time' }}</p>
<p style="font-size: 0.85rem; color:#6b7280; margin-top:-8px;"><strong>Generated:</strong> {{ \Carbon\Carbon::now('Asia/Manila')->format('F d, Y h:i A') }}</p>

@if($books->isEmpty())
    <p class="empty-msg">No acquired books found for this period.</p>
@else
<table>
    <thead>
        <tr>
            @if(empty($options['custom_options_applied']) || !empty($options['accession']))
                <th>Accession No.</th>
            @endif
            <th>Title</th>
            <th>Author</th>
            @if(empty($options['custom_options_applied']) || !empty($options['publisher_info']))
                <th>Publisher</th>
                <th>Publication Year</th>
            @endif
            @if(empty($options['custom_options_applied']) || !empty($options['date_acquired']))
                <th>Date Acquired</th>
            @endif
        </tr>
    </thead>
    <tbody>
        @foreach($books as $book)
        <tr>
            @if(empty($options['custom_options_applied']) || !empty($options['accession']))
                <td><strong style="font-family:monospace; color:#800000;">{{ $book->accession_number ?? 'N/A' }}</strong></td>
            @endif
            <td style="font-weight:600;">{{ $book->title }}</td>
            <td style="color:#6b7280;">{{ $book->author ?? 'N/A' }}</td>
            @if(empty($options['custom_options_applied']) || !empty($options['publisher_info']))
                <td>{{ $book->publisher ?? 'N/A' }}</td>
                <td>{{ $book->publication_year ?? 'N/A' }}</td>
            @endif
            @if(empty($options['custom_options_applied']) || !empty($options['date_acquired']))
                <td>{{ $book->created_at ? $book->created_at->format('M d, Y') : 'N/A' }}</td>
            @endif
        </tr>
        @endforeach
    </tbody>
</table>
@endif

<div class="footer">
    Report generated by PUPSJ Libris Nexus &mdash; Polytechnic University of the Philippines San Juan
</div>
</body>
</html>
