<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Book Acquisition Recommendations</title>
    <style>
        body { font-family: 'Segoe UI', system-ui, sans-serif; margin: 40px; color: #1f2937; font-size: 0.9rem; }
        h1 { color: #800000; border-bottom: 3px solid #FFC72C; padding-bottom: 8px; margin-bottom: 4px; }
        .meta { color: #6b7280; font-size: 0.85rem; margin-bottom: 6px; }
        .section-note { font-size: 0.8rem; color: #6b7280; margin-bottom: 10px; font-style: italic; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 10px; }
        th { background: #800000; color: white; padding: 8px 10px; text-align: left; font-weight: 600; font-size: 0.82rem; }
        td { padding: 8px 10px; border-bottom: 1px solid #e5e7eb; font-size: 0.82rem; vertical-align: top; }
        tr:nth-child(even) { background: #f9fafb; }
        .empty-msg { padding: 16px; text-align: center; color: #9ca3af; font-style: italic; font-size: 0.82rem; }
        .footer { margin-top: 40px; font-size: 0.75rem; color: #6b7280; text-align: center; border-top: 1px solid #e5e7eb; padding-top: 14px; }
    </style>
</head>
<body>

<h1>Book Acquisition Recommendations</h1>
<p class="meta"><strong>Generated:</strong> {{ $generated_at->format('F d, Y h:i A') }}</p>
<p class="section-note">Books recommended based on trending subjects and borrowing patterns in the library catalog.</p>

@if($aiSuggestions->isEmpty())
    <p class="empty-msg">No suggestions available at this time. The system may not have enough borrowing data yet.</p>
@else
<table>
    <thead>
        <tr>
            <th>#</th>
            <th>Title</th>
            <th>Author</th>
            <th>Subject</th>
            <th>Year</th>
            <th>Reason</th>
        </tr>
    </thead>
    <tbody>
        @foreach($aiSuggestions as $i => $s)
        <tr>
            <td>{{ $i + 1 }}</td>
            <td><strong>{{ $s['title'] ?? '—' }}</strong></td>
            <td>{{ $s['author'] ?? '—' }}</td>
            <td>{{ $s['subject'] ?? '—' }}</td>
            <td>{{ $s['year'] ?? '—' }}</td>
            <td style="font-size:0.78rem;color:#374151;max-width:200px;">{{ $s['reason'] ?? '—' }}</td>
        </tr>
        @endforeach
    </tbody>
</table>
@endif

<div class="footer">
    Report generated by PUPSJ Libris Nexus
</div>
</body>
</html>
