<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Condemned Books Report</title>
    <style>
        body { font-family: 'Segoe UI', system-ui, sans-serif; margin: 40px; color: #1f2937; }
        .report-header { display: flex; align-items: center; gap: 16px; margin-bottom: 8px; }
        .report-header img { width: 60px; height: 60px; object-fit: contain; }
        .report-title h1 { color: #800000; margin: 0; font-size: 1.4rem; }
        .report-title p { color: #6b7280; margin: 2px 0 0; font-size: 0.85rem; }
        .divider { border: none; border-top: 3px solid #FFC72C; margin: 12px 0 16px; }
        .meta { color: #6b7280; font-size: 0.9rem; margin-bottom: 20px; }
        .meta strong { color: #1f2937; }
        table { width: 100%; border-collapse: collapse; margin: 20px 0; font-size: 0.88rem; }
        th { background: #800000; color: white; padding: 10px 12px; text-align: left; font-weight: 600; font-size: 0.85rem; }
        td { padding: 9px 12px; border-bottom: 1px solid #e5e7eb; vertical-align: top; }
        tr:nth-child(even) { background: #f9fafb; }
        .empty-msg { padding: 24px; text-align: center; color: #6b7280; font-style: italic; }
        .footer { margin-top: 40px; font-size: 0.8rem; color: #6b7280; text-align: center; border-top: 1px solid #e5e7eb; padding-top: 16px; }
    </style>
</head>
<body>

<div class="report-header">
    @if(extension_loaded('gd') && file_exists(public_path('images/pup-logo.png')))
        <img src="{{ public_path('images/pup-logo.png') }}" alt="PUP Logo">
    @endif
    <div class="report-title">
        <h1>Condemned Books Report</h1>
        <p>Polytechnic University of the Philippines – San Juan Branch</p>
        <p>PUPSJ Libris Nexus</p>
    </div>
</div>
<hr class="divider">

<div class="meta">
    <strong>Period:</strong> {{ $periodLabel ?? 'All Time' }}<br>
    <strong>Generated:</strong> {{ \Carbon\Carbon::now('Asia/Manila')->format('F d, Y h:i A') }}<br>
    <strong>Total Condemned:</strong> {{ $books->count() }}
</div>

@if($books->isEmpty())
    <p class="empty-msg">No condemned books found for this period.</p>
@else
<table>
    <thead>
        <tr>
            <th>#</th>
            <th>Accession No.</th>
            <th>Title</th>
            <th>Author</th>
            @if(empty($options['custom_options_applied']) || !empty($options['call_number']))
                <th>Call Number</th>
            @endif
            <th>Condemned Date</th>
            @if(empty($options['custom_options_applied']) || !empty($options['condemned_by']))
                <th>Condemned By</th>
            @endif
            @if(empty($options['custom_options_applied']) || !empty($options['reason']))
                <th>Reason</th>
            @endif
            @if(empty($options['custom_options_applied']) || !empty($options['last_borrower']))
                <th>Last Borrower</th>
            @endif
        </tr>
    </thead>
    <tbody>
        @foreach($books as $index => $book)
        <tr>
            <td>{{ $index + 1 }}</td>
            <td><strong style="font-family:monospace; color:#800000;">{{ $book->accession_number ?? '—' }}</strong></td>
            <td style="font-weight:600;">{{ $book->title }}</td>
            <td style="color:#6b7280;">{{ $book->author ?? '—' }}</td>
            @if(empty($options['custom_options_applied']) || !empty($options['call_number']))
                <td>{{ $book->loc_number ?? $book->call_number ?? '—' }}</td>
            @endif
            <td>{{ $book->condemned_at ? \Carbon\Carbon::parse($book->condemned_at)->format('M d, Y') : '—' }}</td>
            @if(empty($options['custom_options_applied']) || !empty($options['condemned_by']))
                <td>{{ $book->condemned_by ?? '—' }}</td>
            @endif
            @if(empty($options['custom_options_applied']) || !empty($options['reason']))
                <td>{{ $book->condemnation_reason ?? '—' }}</td>
            @endif
            @if(empty($options['custom_options_applied']) || !empty($options['last_borrower']))
                <td>
                    @if($book->last_borrower_info)
                        {{ is_array($book->last_borrower_info) ? ($book->last_borrower_info['name'] ?? '—') : $book->last_borrower_info }}
                    @else
                        —
                    @endif
                </td>
            @endif
        </tr>
        @endforeach
    </tbody>
</table>
@endif

<div class="footer">
    Report generated by PUPSJ Libris Nexus &mdash; Polytechnic University of the Philippines San Juan
</div>
</body>
</html>
