<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Library Statistics Report</title>
    <style>
        body { font-family: 'Segoe UI', system-ui, sans-serif; margin: 40px; color: #1f2937; }
        h1 { color: #800000; border-bottom: 3px solid #FFC72C; padding-bottom: 8px; }
        h2 { color: #800000; border-left: 5px solid #FFC72C; padding-left: 12px; margin-top: 32px; }
        .summary-box { background: #f8f9fc; padding: 16px 20px; border-radius: 10px; margin: 20px 0; }
        .summary-box ul { list-style: none; padding: 0; columns: 2; }
        .summary-box li { margin-bottom: 8px; }
        .summary-box li strong { display: inline-block; min-width: 220px; }
        table { width: 100%; border-collapse: collapse; margin: 16px 0; }
        th { background: #800000; color: white; padding: 10px 12px; text-align: left; font-weight: 600; font-size: 0.9rem; }
        td { padding: 10px 12px; border-bottom: 1px solid #e5e7eb; }
        tr:nth-child(even) { background: #f9fafb; }
        h3 { color: #800000; margin-top: 20px; }
        ul.books-list { list-style: none; padding-left: 20px; }
        ul.books-list li::before { content: "📖 "; }
        .footer { margin-top: 40px; font-size: 0.8rem; color: #6b7280; text-align: center; border-top: 1px solid #e5e7eb; padding-top: 16px; }
    </style>
</head>
<body>
    <h1>Library Statistics Report</h1>
<p><strong>Period:</strong> {{ $periodLabel ?? 'All Time' }}</p>
<p><strong>Generated:</strong> {{ $generated_at instanceof \Carbon\Carbon ? $generated_at->format('F d, Y h:i A') : $generated_at }}</p>

<h2>Summary</h2>
<div class="summary-box">
    <ul>
        <li><strong>Total Books (available copies):</strong> {{ $totalBooks }}</li>
        <li><strong>Total Students:</strong> {{ $totalStudents }}</li>
        <li><strong>Total Borrows:</strong> {{ $totalBorrows }}</li>
        <li><strong>Total Returns (completed):</strong> {{ $totalReturns }}</li>
        <li><strong>Active Users (currently borrowed):</strong> {{ $activeUsers }}</li>
        <li><strong>Archived Books:</strong> {{ $archivedBooks }}</li>
        <li><strong>Condemned Books:</strong> {{ $condemnedBooks ?? 0 }}</li>
    </ul>
</div>

<h2>Student Breakdown by Course</h2>
<table>
    <thead><tr><th>Program</th><th>Number of Students</th></tr></thead>
    <tbody>
        @foreach($courseBreakdown as $course)
        <tr><td>{{ $course->program }}</td><td>{{ $course->total }}</td></tr>
        @endforeach
    </tbody>
</table>

<h2>Most Used Books by Course</h2>
@foreach($mostUsedBooksByCourse as $course => $books)
    <h3 style="margin-top:16px; margin-bottom:8px;">{{ $course }}</h3>
    <table>
        <thead>
            <tr>
                <th style="width:70%;">Book Title</th>
                <th style="width:30%; text-align:right;">Borrow Count</th>
            </tr>
        </thead>
        <tbody>
            @forelse($books as $book)
            <tr>
                <td><strong>{{ $book->title }}</strong></td>
                <td style="text-align:right;">{{ $book->borrow_count }} borrows</td>
            </tr>
            @empty
            <tr>
                <td colspan="2" style="text-align:center; color:#9ca3af; font-style:italic;">No recorded borrows for this course.</td>
            </tr>
            @endforelse
        </tbody>
    </table>
@endforeach

<div class="footer">
    Report generated by PUPSJ Libris Nexus
</div>
</body>
</html>