<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Seasonal Books Recommendations</title>
    <style>
        body { font-family: 'Segoe UI', system-ui, sans-serif; margin: 36px; color: #1f2937; font-size: 13px; }
        h1 { color: #800000; border-bottom: 3px solid #FFC72C; padding-bottom: 8px; margin-bottom: 4px; font-size: 20px; }
        .meta { color: #6b7280; font-size: 12px; margin-bottom: 16px; }
        .season-card { background: #fefce8; border: 1px solid #fef08a; border-left: 5px solid #800000; padding: 12px 16px; border-radius: 8px; margin-bottom: 18px; }
        .season-title { font-size: 15px; font-weight: 700; color: #800000; margin: 0 0 4px; }
        .season-theme { font-size: 12px; font-weight: 600; color: #b45309; margin: 0 0 6px; }
        .season-desc { font-size: 11px; color: #4b5563; margin: 0; line-height: 1.4; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th { background: #800000; color: white; padding: 9px 12px; text-align: left; font-weight: 600; font-size: 11px; text-transform: uppercase; letter-spacing: 0.5px; }
        td { padding: 9px 12px; border-bottom: 1px solid #e5e7eb; font-size: 12px; vertical-align: top; }
        tr:nth-child(even) { background: #f9fafb; }
        .badge { display: inline-block; padding: 2px 8px; border-radius: 12px; font-size: 11px; font-weight: 700; background: #dcfce7; color: #166534; }
        .reason { font-size: 11px; color: #800000; font-weight: 600; }
        .footer { margin-top: 36px; font-size: 11px; color: #6b7280; text-align: center; border-top: 1px solid #e5e7eb; padding-top: 12px; }
    </style>
</head>
<body>

<h1>Seasonal Books Display &amp; Curation Report</h1>
<p class="meta">
    <strong>Generated:</strong> {{ $generated_at->format('F d, Y h:i A') }} &nbsp;|&nbsp;
    <strong>Active Season:</strong> {{ $season['name'] }} ({{ ucfirst($season['active_mode'] ?? 'Auto') }} Mode)
</p>

<div class="season-card">
    <div class="season-title">{{ $season['name'] }}</div>
    <div class="season-theme">Theme: {{ $season['theme'] }}</div>
    <p class="season-desc">{{ $season['description'] }}</p>
</div>

<h2>Curated Books Suggested for Display</h2>
<table>
    <thead>
        <tr>
            <th style="width: 30px;">#</th>
            <th style="width: 90px;">Accession No.</th>
            <th>Book Title</th>
            <th>Author</th>
            <th>Collection / Subject</th>
            <th style="text-align: right; width: 60px;">Copies</th>
            <th>Curation Reason</th>
        </tr>
    </thead>
    <tbody>
        @forelse($suggestedBooks as $i => $book)
        <tr>
            <td style="color:#9ca3af; font-weight:700;">{{ $i + 1 }}</td>
            <td style="font-family:monospace; font-weight:700; color:#800000;">{{ $book->accession_number ?? '—' }}</td>
            <td>
                <div style="font-weight:700; color:#111;">{{ $book->title }}</div>
                @if(!empty($book->edition))
                    <small style="color:#6b7280;">Edition: {{ $book->edition }}</small>
                @endif
            </td>
            <td style="color:#4b5563;">{{ $book->author ?? '—' }}</td>
            <td>
                <div style="font-weight:600; color:#374151;">{{ $book->collection ?? 'General' }}</div>
                <small style="color:#6b7280;">{{ $book->subject ?? '—' }}</small>
            </td>
            <td style="text-align: right;">
                <span class="badge">{{ $book->copies }}</span>
            </td>
            <td class="reason">
                {{ $book->seasonal_reason }}
            </td>
        </tr>
        @empty
        <tr>
            <td colspan="7" style="text-align: center; padding: 24px; color: #9ca3af;">No book recommendations available for this season.</td>
        </tr>
        @endforelse
    </tbody>
</table>

<div class="footer">
    Report generated by PUPSJ Libris Nexus &mdash; Polytechnic University of the Philippines San Juan
</div>
</body>
</html>
