<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Student Borrowing Report</title>
    <style>
        body { font-family: 'Segoe UI', system-ui, sans-serif; margin: 40px; color: #1f2937; }
        h1 { color: #800000; border-bottom: 3px solid #FFC72C; padding-bottom: 8px; }
        h2 { color: #800000; border-left: 4px solid #FFC72C; padding-left: 10px; margin: 26px 0 10px; font-size: 1.15rem; }
        .period-line { color: #6b7280; font-size: 0.95rem; margin-bottom: 16px; }
        table { width: 100%; border-collapse: collapse; margin: 12px 0 20px; font-size: 0.88rem; }
        th { background: #800000; color: white; padding: 9px 12px; text-align: left; font-weight: 600; font-size: 0.85rem; }
        td { padding: 9px 12px; border-bottom: 1px solid #e5e7eb; font-size: 0.86rem; }
        tr:nth-child(even) { background: #f9fafb; }
        .empty-msg { padding: 24px; text-align: center; color: #6b7280; font-style: italic; }
        .footer { margin-top: 40px; font-size: 0.8rem; color: #6b7280; text-align: center; border-top: 1px solid #e5e7eb; padding-top: 16px; }
    </style>
</head>
<body>
<h1>Student Borrowing Report</h1>
<p class="period-line"><strong>Period:</strong> {{ $periodLabel ?? 'All Time' }}</p>
<p style="font-size: 0.85rem; color:#6b7280; margin-top:-8px;"><strong>Generated:</strong> {{ \Carbon\Carbon::now('Asia/Manila')->format('F d, Y h:i A') }}</p>

{{-- Program / Course Breakdown --}}
@if((empty($options['custom_options_applied']) || !empty($options['program_usage'])) && !empty($courseBreakdown) && $courseBreakdown->isNotEmpty())
<h2>Program / Course Breakdown</h2>
<table>
    <thead>
        <tr>
            <th>Academic Program</th>
            <th style="text-align:right;">Registered Patrons</th>
        </tr>
    </thead>
    <tbody>
        @foreach($courseBreakdown as $course)
        <tr>
            <td style="font-weight:600;">{{ $course->program ?: 'Unspecified Program' }}</td>
            <td style="font-weight:700; text-align:right;">{{ $course->total }}</td>
        </tr>
        @endforeach
    </tbody>
</table>
@endif

{{-- Detailed Transaction Logs --}}
@if(empty($options['custom_options_applied']) || !empty($options['timestamp_logs']))
<h2>Detailed Transaction Logs</h2>
@if($records->isEmpty())
    <p class="empty-msg">No transaction records found for this period.</p>
@else
<table>
    <thead>
        <tr>
            <th>Student Number</th>
            <th>Student Name</th>
            <th>Program</th>
            <th>Book Title</th>
            <th>Accession No.</th>
            <th>Borrowed At</th>
            <th>Returned At</th>
            <th>Status</th>
        </tr>
    </thead>
    <tbody>
        @foreach($records as $usage)
        <tr>
            <td><strong style="font-family:monospace; color:#800000;">{{ $usage->student->student_number ?? 'N/A' }}</strong></td>
            <td>
                @if($usage->student)
                    {{ $usage->student->first_name }} {{ $usage->student->last_name }}
                @else
                    N/A
                @endif
            </td>
            <td>{{ $usage->student->program ?? 'N/A' }}</td>
            <td><strong>{{ $usage->book->title ?? 'N/A' }}</strong></td>
            <td><span style="font-family:monospace; color:#800000;">{{ $usage->book->accession_number ?? 'N/A' }}</span></td>
            <td>{{ $usage->time_in ? $usage->time_in->format('M d, Y h:i A') : 'N/A' }}</td>
            <td>
                @if($usage->status === 'active')
                    <span style="color:#b45309; font-weight:600;">Active Loan</span>
                @elseif($usage->time_out)
                    {{ $usage->time_out->format('M d, Y h:i A') }}
                @else
                    N/A
                @endif
            </td>
            <td>
                <span style="font-weight:700; color:{{ $usage->status === 'active' ? '#b45309' : '#166534' }};">
                    {{ ucfirst($usage->status) }}
                </span>
            </td>
        </tr>
        @endforeach
    </tbody>
</table>
@endif
@endif

<div class="footer">
    Report generated by PUPSJ Libris Nexus &mdash; Polytechnic University of the Philippines San Juan
</div>
</body>
</html>
